### ISSUE TITLE
Meaning behind "consensus_direction"

### ISSUE THREAD

**Issue by pokedthefrog** [saezlab/omnipath#24]
I am a bit confused about the `consensus_direction` property. As I understand, it does not actually refer to direction (that is, going from A to B or the reverse), but instead captures whether consensus exists on the _sign_ of the interaction. It seems that the following holds: 

`consensus_direction = consensus_stimulation | consensus_inhibition`

Would that be correct? If so, the current name could be a bit confusing and, for example, `consensus_sign` might be more appropriate.

Thanks for any help with this! 😊

**Comment by pokedthefrog** [comment]
Hello Denes, 

Thank you very much for the prompt response! The difference between them is now a bit more clear to me but, just to make sure, the `is_directed` column refers to actual directionality of the interaction (and seems to be `True` for all of them, at least when using default parameters), while the `consensus_direction` column seems to instead provide information on whether consensus exists on the effect sign (stimulation or inhibition) of each interaction.

That said, I will start using the `is_stimulation` and `is_inhibition` columns, as you suggested. Thank you!

**Comment by deeenes** [comment]
Just a little clarification: OmniPath contains a few undirected interactions, but those are only returned with the `directed=no` parameter. The `consensus_direction` column is `True` if more evidences support the `source -> target` than the `target -> source` direction. The `consensus_stimulation` is `True` if more evidences support that the `source -> target` interaction is stimulatory rather than inhibitory. Consensus on the `target -> source` interaction is shown in another row, if any resource support that direction.

**Comment by pokedthefrog** [comment]
Thanks a lot, that clears my confusion!

**Comment by pokedthefrog** [comment]
I feel the need to re-open this, as I've come across some inconsistencies (or what might very well be a lack of understanding on my part). 

It seems that the `consensus_direction` attribute of non-mutual (unidirectional) interactions can either be `True` or `False`. At first, my understanding was that `consensus_direction` set to `True` would imply one of two possibilities: 1. either the interaction is non-mutual and the reverse direction not supported by any sources/references, or 2. the reverse interaction exists in the DataFrame with its `consensus_direction` attribute set to `False`.

As an example, [going through the TF-target interactions](https://omnipathdb.org/interactions/?datasets=tf_target,dorothea), I can see that `P01106 → O14746` only exists in one direction and its `consensus_direction` is set to `True`. However, `Q9UQE7 → P14316` also appears to be unidirectional, yet its `consensus_direction` is `False`. 

Would that be expected behaviour? Thanks a lot again for the help!

**Comment by deeenes** [comment]
Hi @pokedthefrog,

Indeed this seems contradictory first, but the reason is that all datasets (of the same interaction type) are considered when creating the "consensus" columns, not only the ones you have in your particular query. 

```
library(OmnipathR)
library(dplyr)

grn <- import_transcriptional_interactions()
partners <- c('Q9UQE7', 'P14316')
grn %>% filter(source %in% partners & target %in% partners)

# A tibble: 2 × 16
  source target source_genesymbol target_genesymbol is_directed is_stimulation is_inhibition consensus_direction consensus_stimulation consensus_inhibition sources                   references         curation_effort dorothea_level n_references n_resources
  <chr>  <chr>  <chr>             <chr>                   <dbl>          <dbl>         <dbl>               <dbl>                 <dbl>                <dbl> <chr>                     <chr>                        <dbl> <chr>                 <dbl>       <int>
1 P14316 Q9UQE7 IRF2              SMC3                        1              1             0                   1                     1                    0 CollecTRI;ExTRI_CollecTRI CollecTRI:10082588               1 NA                        1           1
2 Q9UQE7 P14316 SMC3              IRF2                        1              0             0                   0                     0                    0 ENCODE-distal             NA                               0 NA                        0           1
```

The direction that you mention (2nd row above) is from the "tf_target" dataset, while the opposite interaction is from the "collectri" dataset. The former has no literature references, the latter has one, hence the consensus direction will prefer the one with reference.

Best,

Denes

**Comment by pokedthefrog** [comment]
@deeenes Thank you so much; I hadn't realised "CollecTRI" had been added and (incorrectly) assumed my query was pulling all transcriptional interactions. It makes perfect sense now!
