### ISSUE TITLE
omnipath connection on Amazon web service and my PC

### ISSUE THREAD

**Issue by sophieRAIBAUD** [saezlab/omnipath#25]
Dear all
again many thanks for your help on spatial transcriptomic data ....

I have some trouble using squidpy.gr.ligrec : error message: Failed to establish a new connection: [Errno 110] Connection timed out'
But I can connect to omnipath using :
wget https://omnipathdb.org/ --no-check-certificate
instead of:
wget https://omnipathdb.org/
is there a way to add the option no-check-certificate in the squidpy.gr.ligrec function ?
I have tried to releave the security using os.environ["PYTHONHTTPSVERIFY"]="0" but it does not work
Many thanks
Sophie

**Comment by deeenes** [comment]
Hello Sophie,

We see two issues here: the "connection timed out" says the connection could not be established within 600 seconds, the default connect timeout in the `omnipath` package.

The `no-check-certificate` option of `wget` bypasses the certificate validity check for https connections. It is useful if otherwise `wget` would deem the certificate invalid, most likely because its certificate store is out of date. Have you got any error about invalid certificates? If so, the best would be to update the certificate store of your OS. The `omnipath` module uses the [Python module `requests`](https://requests.readthedocs.io/en/latest/) to perform downloads. `requests` accepts the option `verify = False` which is synonymous to `no-check-certificate`, however, at the moment we don't have a way in the `omnipath` package to pass this option. Though would be easy to add.

To address this issue more information would be useful:

```
from http.client import HTTPConnection
HTTPConnection.debuglevel = 1

import requests

req = requests.request('GET', 'https://omnipathdb.org/intercell', timeout = 600)
```

Finally, yesterday our server run out of disk space, this might have caused some unusual errors, apologies about that.

Best,

Denes

**Comment by sophieRAIBAUD** [comment]
Thanks Denes !
when I run your script, I get this error

SSLError: HTTPSConnectionPool(host='omnipathdb.org', port=443): Max retries exceeded with url: /intercell (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)')))

**Comment by deeenes** [comment]
The error message here is `self-signed certificate in certificate chain`. That means the certificate stores on your systems (both the Amazon VM and your home computer) are out of date. The chain of trust for the SSL certificates of the `omnipathdb.org` server looks like this:

```
Path #1: Trusted
1     Sent by server     status.omnipathdb.org
Fingerprint SHA256: 36563883ef24694631c2047d592da286d9a92970dec703de7a0c5f13fca96c7f
Pin SHA256: YPaMTdkiT7N1IrmYmktCxaYyslKvYijAETwZG/kOsP8=
RSA 2048 bits (e 65537) / SHA256withRSA
2     Sent by server     R3
Fingerprint SHA256: 67add1166b020ae61b8f5fc96813c04c2aa589960796865572a3c7e737613dfd
Pin SHA256: jQJTbIh0grw0/1TkHSumWb+Fs0Ggogr621gT3PvPKG0=
RSA 2048 bits (e 65537) / SHA256withRSA
3     In trust store     ISRG Root X1   Self-signed    
Fingerprint SHA256: 96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6
Pin SHA256: C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=
RSA 4096 bits (e 65537) / SHA256withRSA
```

You can see the info above and more details at [SSLabs](https://www.ssllabs.com/ssltest/analyze.html?d=omnipathdb.org). As you see above, the trust in the server's certificate is verified in two steps, first it is signed by the R3 certificate, which is then signed by the ISGR Root X1. This latter is also self-signed, but it is a root certificate, it should be distributed with all up-to-date (younger than 7 years old) SSL clients, because about quarter of a billion web servers rely on it. I think if it was in your trust store then it would be trusted, but it's missing from there, so it's retrieved from our server by the SSL client, and then it's not trusted because it's not signed by any further certificate.

How the certificate store for your Python is maintained largely depends on your environment (your OS, other tools potentially involved, like Brew, Conda, Docker, etc). I recommend to look at the documentation from your Python distributor to find out how to update the certificates.

You can also manually override the certificate store for the `requests` Python module, by passing the name of the certificate file by the `verify` argument, e.g.:

```
from http.client import HTTPConnection
HTTPConnection.debuglevel = 1

import requests

req = requests.request(
    'GET',
    'https://omnipathdb.org/intercell',
    timeout = 600,
    verify = 'my-trusted-certs.crt',
)
```

The above method is useful for debugging issues. [Here is some more info](https://stackoverflow.com/a/42982144/854988) about how `requests` gets its certificates by default.

Best,

Denes

**Comment by sophieRAIBAUD** [comment]
dear Denes,
The problem is that I am working on confidential data and I can not send it to omnipath in order to do the analysis.
could you just tell me how omnipath is working ?
is there a way to get the database for me ?
Many thanks 
Sophie

**Comment by deeenes** [comment]
Hi, Unfortunately I missed to answer this last year, I hope you found a good solution. For the record, we've just added fallback features to the OmniPath clients that could likely work around issues like this one. How OmniPath works is described in detail in our papers and our [webpage](https://omnipathdb.org/). Briefly, the database content is available primarily by web service clients, through a simple REST API, but [static TSV dumps](https://archive.omnipathdb.org/) are also available.
