### ISSUE TITLE
source, target, ligand and receptor

### ISSUE THREAD

**Issue by wangjiawen2013** [saezlab/omnipath#26]
Hi,
I am confused with some glossaries (source, target, ligand and receptor), and here is an related issue.
https://github.com/scverse/squidpy/issues/499#issuecomment-1139211386

**Comment by deeenes** [comment]
Hi,

I haven't noticed this issue until now, I hope you've already found a satisfying answer!

Indeed, in OmniPath source and target refers to the flow of information or direction of causality in case of molecular interactions. Of course this simple scheme sometimes is not able to cover biological reality. And about cell-cell communication, ligand is by definition source and receptor is target, just because the information flow is from ligand to receptor. In OmniPath we try to cover other kind of cell-cell communication agents too, hence we call them transmitters and receivers, e.g. a channel or transporter is a receiver, because altering its behaviour potentially has an impact on the expressing cell.

Best,

Denes
