### ISSUE TITLE
Query on change in number of interactions

### ISSUE THREAD

**Issue by Tama-sha** [saezlab/omnipath#47]
Hello

I had previously downloaded omnipath interactions from the webclient in April and downloaded another set today ie 25th May. I see a massive change in interaction count. 
I wanted to confirm if there has been an update or am i missing something. 

Regards
 Note: List 2 is older and List 1 is new download
![image](https://github.com/saezlab/omnipath/assets/106139199/b4f94856-1183-4ec5-9d4b-673357cf6c29)

**Comment by deeenes** [comment]
Hello @Tama-sha,

This is most likely [due to our May 18 update](https://archive.omnipathdb.org/README.txt) (and the April 5 update also can contribute if your first download was before that day). Briefly, we improved the way how interactions are assigned to datasets (such as "omnipath", "pathwayextra", "kinaseextra" and "ligrecextra"). Before the datasets were simply sets of resource names; now each individual evidence carries its dataset label and these are assigned correctly for each interaction. The ~10k interactions difference that you see is more or less the size of change I find normal after this update. Web service data from previous periods is available [here](https://archive.omnipathdb.org/).

I hope this helps, and apologies for the inconvenience.

Best,

Denes

**Comment by Tama-sha** [comment]
Hello @deeenes 

This is very helpful! Thank you so much for clarifying.

Regards
Tamanna
